import org.springframework.web.filter.ShallowEtagHeaderFilter.HttpStreamingAwareContentCachingResponseWrapper;
public class FunctionUse3276 {
public void funcUse() {
HttpStreamingAwareContentCachingResponseWrapper httpstreamingawarecontentcachingresponsewrapper = new HttpStreamingAwareContentCachingResponseWrapper();
httpstreamingawarecontentcachingresponsewrapper.getWriter();
}
}