import org.springframework.web.filter.ShallowEtagHeaderFilter.HttpStreamingAwareContentCachingResponseWrapper;
public class FunctionUse3277 {
public void funcUse() {
HttpStreamingAwareContentCachingResponseWrapper httpstreamingawarecontentcachingresponsewrapper = new HttpStreamingAwareContentCachingResponseWrapper();
httpstreamingawarecontentcachingresponsewrapper.getOutputStream();
}
}