import org.springframework.web.filter.ShallowEtagHeaderFilter.HttpStreamingAwareContentCachingResponseWrapper;
public class FunctionUse3278 {
public void funcUse() {
HttpStreamingAwareContentCachingResponseWrapper httpstreamingawarecontentcachingresponsewrapper = new HttpStreamingAwareContentCachingResponseWrapper();
}
}